// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuVdWX_gJyE05zMhv9wcHs6m6BGOilks',
    appId: '1:877606470412:web:0eb5ebad167a8c75547f29',
    messagingSenderId: '877606470412',
    projectId: 'shopping-f7bf1',
    authDomain: 'shopping-f7bf1.firebaseapp.com',
    storageBucket: 'shopping-f7bf1.appspot.com',
    measurementId: 'G-G61TY6BNL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2s5Ne-SJMkfpXiF2CVCXG1Q1jx-W4ELI',
    appId: '1:877606470412:android:09d95284e3fefafa547f29',
    messagingSenderId: '877606470412',
    projectId: 'shopping-f7bf1',
    storageBucket: 'shopping-f7bf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSbVh0MEvtm4NukWoYsqqHYofkVDAahA',
    appId: '1:877606470412:ios:b986e7990d6b2a3b547f29',
    messagingSenderId: '877606470412',
    projectId: 'shopping-f7bf1',
    storageBucket: 'shopping-f7bf1.appspot.com',
    iosClientId: '877606470412-gjm7pk6nq13qnmh8b6824vhg3h4krju5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );
}
